version: "3"

vars:
  GREETING: Hello, World!
  DIR_ENV: .venv

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  venv:init:
    desc: "create venv and install mandatory packages"
    cmds:
      - |
        if [ -d  {{.DIR_ENV}} ]; then
          echo "{{.DIR_ENV}} is already present"
        else
          python3 -m venv {{.DIR_ENV}} --prompt team3
        fi
        {{.DIR_ENV}}/bin/pip install -r requirements.txt
      - task: git:hooks

  git:hooks:
    desc: "install pre-commit"
    cmds:
      - "{{.DIR_ENV}}/bin/pre-commit install --hook-type pre-commit --hook-type pre-merge-commit --hook-type post-merge"
